title: Priyavrat Sharma
logo: "/profile.png?raw=true"
description: > 
 Backend Engineer
  <br><br>
  <a href="mailto:priyavrat18@gmail.com">priyavrat18@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/priyavrat18/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/priyavrat18/">Github</a> 
theme: jekyll-theme-minimal